version: 2
jobs:
  deploy-job:
    working_directory: ~/app
    docker:
      - image: circleci/node:6.11
    steps:
      - checkout
      - restore_cache:
          key: asake-button-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
      - run:
          name: Install dependencies
          command: npm install && npm run deps
      - run:
          name: Deploy Master to Firebase
          command: npm run deploy -- --non-interactive
      - save_cache:
          key: asake-button-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
          paths:
            - ~/app/node_modules

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-job
          filters:
            branches:
              only: master
