version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:6.11
    steps:
      - run:
        name: Deploy Master to Firebase
        command: npm run deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: introduce-circleci
